const express = require("express");
const path = require("path");
const fs = require("fs");
const PDFDocument = require("pdfkit");

const casesModel = require("../models/cases");
const analysisModel = require("../models/analysis");
const misc = require("../models/misc");
const { requireAuth, requireRole } = require("../middleware/auth");

const router = express.Router();

const REPORTS_DIR = path.join(__dirname, "..", "..", "uploads", "reports");
fs.mkdirSync(REPORTS_DIR, { recursive: true });

router.get("/", requireAuth, async (req, res) => {
  const rows = await misc.listReports();
  const reports = await Promise.all(
    rows.map(async (r) => {
      const c = await casesModel.findRawById(r.case_id);
      return {
        id: r.report_code,
        caseId: c ? c.case_code : r.case_id,
        patientId: c ? c.patient_code : "",
        signedBy: r.signed_by,
        date: r.created_at,
        status: c ? c.diagnosis_status : "",
      };
    })
  );
  res.json({ reports });
});

router.post("/:caseId/generate", requireAuth, requireRole("admin", "pathologist"), async (req, res) => {
  const caseRow = await casesModel.findRawByCaseCode(req.params.caseId);
  if (!caseRow) return res.status(404).json({ error: "Case not found." });
  const caseData = await casesModel.findByCaseCode(req.params.caseId);
  const analysis = await analysisModel.findLatestForCase(caseRow.id);

  const reportCode = await misc.nextReportCode();
  const fileName = `${reportCode}.pdf`;
  const filePath = path.join(REPORTS_DIR, fileName);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // FIX 1: Removed { align: "left" } so text continues horizontally inline
  doc.fontSize(20)
     .fillColor("#1a2b4c")
     .text("AI-Path Assist", { continued: true })
     .fillColor("#666")
     .fontSize(10)
     .text("   Clinical Pathology Intelligence Platform");

  doc.moveDown(0.3);
  doc.strokeColor("#1a2b4c").lineWidth(2).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(1);

  doc.fontSize(16).fillColor("#000").text("Diagnostic Report", { align: "left" });
  doc.fontSize(10).fillColor("#666").text(`Report ID: ${reportCode}    Generated: ${new Date().toISOString().slice(0, 19).replace("T", " ")}`);
  doc.moveDown(1);

  doc.fontSize(12).fillColor("#000").text("Patient & Specimen", { underline: true });
  doc.fontSize(10).fillColor("#333");
  doc.text(`Case ID: ${caseData.id}`);
  doc.text(`Patient ID: ${caseData.patientId}`);
  doc.text(`Patient Name: ${caseData.patientName}`);
  doc.text(`Age / Gender: ${caseData.age} / ${caseData.gender}`);
  doc.text(`Specimen Type: ${caseData.specimenType}`);
  doc.text(`Date Added: ${caseData.dateAdded}`);
  doc.text(`Assigned Pathologist: ${caseData.assignedTo || "Unassigned"}`);
  doc.moveDown(1);

  doc.fontSize(12).fillColor("#000").text("AI Inference Summary", { underline: true });
  doc.moveDown(0.3);
  if (analysis && analysis.metrics && analysis.metrics.length) {
    analysis.metrics.forEach((m) => {
      doc.fontSize(10).fillColor("#333").text(`${m.label}:  ${m.value}${m.unit ? " " + m.unit : ""}   [${m.tag}]`);
    });
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor("#888").text(`Engine: ${analysis.engineVersion}`);
    if (analysis.slideUrl) {
      const slideAbs = path.join(__dirname, "..", "..", "uploads", analysis.slideUrl.replace("/files/", ""));
      if (fs.existsSync(slideAbs)) {
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor("#000").text("Focal Point Image:");
        try {
          // FIX 2: Open image to calculate rendered height & advance doc.y past the image
          const img = doc.openImage(slideAbs);
          const imgWidth = 260;
          const imgHeight = (img.height / img.width) * imgWidth;

          doc.image(img, { width: imgWidth });
          doc.y += imgHeight + 5; // Manually advance Y cursor past image + margin
        } catch (e) {
          // ignore image embed issues
        }
      }
    }
  } else {
    doc.fontSize(10).fillColor("#888").text("No AI analysis has been completed for this case yet.");
  }
  doc.moveDown(1);

  doc.fontSize(12).fillColor("#000").text("Clinical Notes", { underline: true });
  doc.moveDown(0.3);
  if (caseData.notes && caseData.notes.length) {
    caseData.notes.forEach((n) => {
      doc.fontSize(10).fillColor("#333").text(`${n.time} — ${n.author}: ${n.text}`);
    });
  } else {
    doc.fontSize(10).fillColor("#888").text("No clinical notes recorded.");
  }
  doc.moveDown(1.5);

  doc.fontSize(10).fillColor("#000").text(`Digitally signed by: ${req.user.name}`);
  doc.fontSize(9).fillColor("#888").text(`${req.user.institution} · ${new Date().toISOString()}`);
  doc.fontSize(8).fillColor("#aaa").moveDown(0.5).text("This report was generated by AI-Path Assist. AI-derived metrics are decision-support only and require pathologist review.", { width: 495 });

  doc.end();

  stream.on("finish", async () => {
    const report = await misc.createReport({ caseId: caseRow.id, signedBy: req.user.name, filePath: `reports/${fileName}`, reportCode });
    await casesModel.approveReport(req.params.caseId);
    await misc.logAction({ actorId: req.user.id, actorName: req.user.name, action: "Generated diagnostic report", target: req.params.caseId });
    res.status(201).json({ report: { id: report.report_code, downloadUrl: `/files/reports/${fileName}` } });
  });

  stream.on("error", (err) => {
    res.status(500).json({ error: "Failed to generate PDF: " + err.message });
  });
});

module.exports = router;